import { WorkflowStep, SystemInvariant, ToolAnalysis } from "./types";

export const WORKFLOW_STEPS: WorkflowStep[] = [
  {
    id: 1,
    displayId: "01",
    title: "Brainstorming & Debate",
    tool: "Gemini Flash",
    icon: "lightbulb",
    colorClass: "bg-indigo-600",
    purpose:
      "Lightweight brainstorming and idea debate. Serves as a scratchpad for divergent thinking. Only 'flash' mode is used.",
    outputs: ["Exploratory ideas", "Non-authoritative drafts"],
    invariant: "Outputs are exploratory, not authoritative.",
    isSystem: false,
    links: [
      { label: "Gemini", url: "https://gemini.google.com" },
      {
        label: "Custom Instructions",
        url: "https://gemini.google.com/saved-info",
      },
    ],
  },
  {
    id: 2,
    displayId: "02",
    title: "Translation to LLM",
    tool: "Microsoft Copilot",
    icon: "translate",
    colorClass: "bg-indigo-600",
    purpose:
      "Translate raw ideas into clear, structured prompts suitable for LLM processing. Ideas are expressed as actionable, unambiguous instructions.",
    outputs: ["Structured prompts", "Clarified intent"],
    invariant:
      "Clarification: Translation must clarify intent, not just pass instructions downstream.",
    isSystem: false,
    links: [
      { label: "Microsoft Copilot", url: "https://copilot.microsoft.com" },
    ],
  },
  {
    id: 3,
    displayId: "03",
    title: "Feature Roadmap",
    tool: "ChatGPT (OpenAI)",
    icon: "map",
    colorClass: "bg-indigo-600",
    purpose:
      "Expand translated ideas into feature descriptions, reviews, and roadmap documents. Acts as the feature planning layer.",
    outputs: ["Feature descriptions", "Roadmap documents", "Evaluations"],
    invariant: "Drafts only, subject to verification.",
    isSystem: false,
    links: [{ label: "OpenAI ChatGPT", url: "https://chatgpt.com" }],
  },
  {
    id: 8,
    displayId: "!",
    title: "Repo Dump (Context Reset)",
    tool: "Repomix / RepoLiner",
    icon: "backup",
    colorClass: "bg-rose-600",
    purpose:
      "Convert the entire repository into a single Markdown or XML file to reset AI context. Use Repomix for full-featured packing (token counting, secret detection) or RepoLiner for lightweight snapshots.",
    outputs: ["AI-friendly Repo Pack", "Clean Token Slate"],
    invariant:
      "Repo Dump & Token Stability: Repository must be re-fed before Step 4.",
    isSystem: true,
    isCritical: true,
    links: [
      { label: "Repomix GitHub", url: "https://github.com/yamadashy/repomix" },
      {
        label: "RepoLiner GitHub",
        url: "https://github.com/davidtiberias/RepoLiner",
      },
    ],
  },
  {
    id: 4,
    displayId: "04",
    title: "Task Generation",
    tool: "Google AI Studio",
    icon: "psychology",
    colorClass: "bg-indigo-600",
    purpose:
      "Convert roadmap into executable tasks using 'thinking/pro' mode with top-p=0. This ensures deterministic, reproducible output.",
    outputs: ["Deterministic task list", "Reproducible steps"],
    invariant: "Determinism: Tasks must be reproducible and free of ambiguity.",
    isSystem: false,
    links: [{ label: "Google AI Studio", url: "https://aistudio.google.com" }],
  },
  {
    id: 5,
    displayId: "05",
    title: "Agent Execution",
    tool: "Google Antigravity",
    icon: "rocket_launch",
    colorClass: "bg-indigo-600",
    purpose:
      "Execute the tasks generated by AI Studio. This is the operational agent carrying out the planned actions.",
    outputs: ["Code execution", "Terminal logs", "Completed features"],
    invariant:
      "Isolation: Execution is isolated from planning to prevent scope bleed.",
    isSystem: false,
    links: [
      { label: "Google Antigravity", url: "https://antigravity.google/" },
    ],
  },
  {
    id: 6,
    displayId: "06",
    title: "Debugging",
    tool: "Google Search AI Mode",
    icon: "bug_report",
    colorClass: "bg-indigo-600",
    purpose:
      "Identify errors, trace issues, and validate fixes. Debugging must be contextual, using raw terminal logs as input.",
    outputs: ["Error identification", "Trace analysis", "Fix validation"],
    invariant: "Debugging must be contextual, using raw logs as input.",
    isSystem: false,
    links: [{ label: "Google Search AI", url: "https://google.com/ai" }],
  },
  {
    id: 9,
    displayId: "!",
    title: "Repo Dump (Debug Refresh)",
    tool: "Repomix / RepoLiner",
    icon: "backup",
    colorClass: "bg-rose-600",
    purpose:
      "Re-ingest the repository state after execution to ensure debugging tools see the current errors and code version. Repomix is recommended for complex debugging context.",
    outputs: ["Updated Code Context", "Stable Token Count"],
    invariant: "Repo Dump: Ensures fixes are based on current state.",
    isSystem: true,
    isCritical: true,
    links: [
      { label: "Repomix GitHub", url: "https://github.com/yamadashy/repomix" },
      {
        label: "RepoLiner GitHub",
        url: "https://github.com/davidtiberias/RepoLiner",
      },
    ],
  },
  {
    id: 7,
    displayId: "07",
    title: "Solution Feedback Loop",
    tool: "Feedback Integration",
    icon: "sync_problem",
    colorClass: "bg-indigo-600",
    purpose:
      "Feed verified debugging solutions back into Step 4 (Task Generation) to regenerate tasks, closing the loop.",
    outputs: ["Corrected Task List", "Regression prevention"],
    invariant:
      "Fixes must be verified before re-feeding to prevent regression.",
    isSystem: false,
    links: [{ label: "Google AI Studio", url: "https://aistudio.google.com" }],
  },
];

export const SYSTEM_INVARIANTS: SystemInvariant[] = [
  {
    id: "RepoDumpInvariant",
    title: "Repo Dump Invariant",
    icon: "backup",
    description:
      "The repository must be re-fed in Markdown format before Task Generation (Step 4) and Debugging (Step 6). This ensures the AI operates on the absolute latest code state.",
  },
  {
    id: "TokenStabilityInvariant",
    title: "Token Stability Invariant",
    icon: "delete_forever",
    description:
      "Old chats and files must be deleted before new dumps are ingested. This prevents context window overflow and eliminates hallucinations caused by stale data.",
  },
  {
    id: "ClarificationInvariant",
    title: "Clarification Invariant",
    icon: "translate",
    description:
      "The Translation Layer (Copilot) must clarify intent, not just forward instructions. Ambiguities must be resolved here, never passed downstream.",
  },
  {
    id: "DeterminismInvariant",
    title: "Determinism Invariant",
    icon: "rule",
    description:
      'Task Generation (AI Studio) must use top-p=0. Tasks must be reproducible, unambiguous, and free of "creative" randomness.',
  },
  {
    id: "IsolationInvariant",
    title: "Isolation Invariant",
    icon: "block",
    description:
      'Execution (Antigravity) is strictly isolated from planning. The "hands" (Agent) do not decide the "strategy" (Studio).',
  },
];

export const TOOL_ANALYSIS: ToolAnalysis[] = [
  {
    step: 1,
    tool: "Gemini Flash",
    role: "Brainstorming (Flash Mode)",
    strength: "Fast, divergent thinking.",
    weakness: "Shallow reasoning, noisy output.",
  },
  {
    step: 2,
    tool: "Microsoft Copilot",
    role: "Translation to LLM",
    strength: "Compiles raw ideas into structured prompts.",
    weakness: "Single point of failure if intent is mis-framed.",
  },
  {
    step: 3,
    tool: "ChatGPT (OpenAI)",
    role: "Roadmap & Features",
    strength: "Comprehensive deliverables.",
    weakness: "Scope creep (over-specifying).",
  },
  {
    step: 4,
    tool: "Google AI Studio",
    role: "Task Generation (top-p=0)",
    strength: "Deterministic, reproducible tasks.",
    weakness: "Rigid; may miss creative edge cases.",
  },
  {
    step: 5,
    tool: "Antigravity",
    role: "Execution Agent",
    strength: "Isolated execution.",
    weakness: "Black-box; hard to debug if plan is bad.",
  },
  {
    step: 6,
    tool: "Search AI Mode",
    role: "Debugging",
    strength: "Direct log ingestion.",
    weakness: "Requires raw logs; can be noisy.",
  },
  {
    step: 7,
    tool: "Feedback Loop",
    role: "Solution Integration",
    strength: "Closes development loop.",
    weakness: "Risk of re-introducing bugs if verification is skipped.",
  },
  {
    step: 0,
    tool: "Repomix",
    role: "Full Repo Packer",
    strength:
      "AI-friendly formats (XML/MD/JSON), token counting, secret detection.",
    weakness: "Higher complexity than scripts.",
    constraint:
      "Best for feeding repos into AI for code review or refactoring.",
  },
  {
    step: 0,
    tool: "RepoLiner",
    role: "Basic File Merger",
    strength: "Lightweight, quick Markdown snapshots, simple whitelist.",
    weakness: "No advanced features like token counting.",
    constraint: "Best for quick snapshots of small projects.",
  },
];

export const getWorkflowContext = (): string => {
  const steps = WORKFLOW_STEPS.map(
    (s) =>
      `[Step ${s.displayId}] ${s.title}: ${s.purpose}\nInvariant: ${s.invariant}`
  ).join("\n\n");

  const invariants = SYSTEM_INVARIANTS.map(
    (i) => `- ${i.title}: ${i.description}`
  ).join("\n");

  return `Vibecoding Workflow Context:\n\nSTEPS:\n${steps}\n\nSYSTEM INVARIANTS:\n${invariants}`;
};
